/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as authOtpRouteImport } from './routes/(auth)/otp'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as ExperienceExperienceIdRouteImport } from './routes/experience/$experienceId'
import { Route as ProjectProjectIdRouteImport } from './routes/project/$projectId'
import { Route as AuthenticatedAboutIndexRouteImport } from './routes/_authenticated/about/index'
import { Route as AuthenticatedAboutAboutIdRouteImport } from './routes/_authenticated/about/$aboutId'
import { Route as AuthenticatedAboutNewRouteImport } from './routes/_authenticated/about/new'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard/index'
import { Route as AuthenticatedEducationIndexRouteImport } from './routes/_authenticated/education/index'
import { Route as AuthenticatedEducationEducationIdRouteImport } from './routes/_authenticated/education/$educationId'
import { Route as AuthenticatedEducationNewRouteImport } from './routes/_authenticated/education/new'
import { Route as AuthenticatedErrorsErrorRouteImport } from './routes/_authenticated/errors/$error'
import { Route as AuthenticatedExperiencesIndexRouteImport } from './routes/_authenticated/experiences/index'
import { Route as AuthenticatedExperiencesExperienceIdRouteImport } from './routes/_authenticated/experiences/$experienceId'
import { Route as AuthenticatedExperiencesNewRouteImport } from './routes/_authenticated/experiences/new'
import { Route as AuthenticatedHeroIndexRouteImport } from './routes/_authenticated/hero/index'
import { Route as AuthenticatedHeroHeroIdRouteImport } from './routes/_authenticated/hero/$heroId'
import { Route as AuthenticatedHeroNewRouteImport } from './routes/_authenticated/hero/new'
import { Route as AuthenticatedProjectsIndexRouteImport } from './routes/_authenticated/projects/index'
import { Route as AuthenticatedProjectsProjectIdRouteImport } from './routes/_authenticated/projects/$projectId'
import { Route as AuthenticatedProjectsNewRouteImport } from './routes/_authenticated/projects/new'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedSettingsAccountRouteImport } from './routes/_authenticated/settings/account'
import { Route as AuthenticatedSkillsIndexRouteImport } from './routes/_authenticated/skills/index'
import { Route as AuthenticatedSkillsSkillIdRouteImport } from './routes/_authenticated/skills/$skillId'
import { Route as AuthenticatedSkillsNewRouteImport } from './routes/_authenticated/skills/new'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const authOtpRoute = authOtpRouteImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ExperienceExperienceIdRoute = ExperienceExperienceIdRouteImport.update({
  id: '/experience/$experienceId',
  path: '/experience/$experienceId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectProjectIdRoute = ProjectProjectIdRouteImport.update({
  id: '/project/$projectId',
  path: '/project/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAboutIndexRoute = AuthenticatedAboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAboutAboutIdRoute =
  AuthenticatedAboutAboutIdRouteImport.update({
    id: '/about/$aboutId',
    path: '/about/$aboutId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAboutNewRoute = AuthenticatedAboutNewRouteImport.update({
  id: '/about/new',
  path: '/about/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/dashboard/',
    path: '/dashboard/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEducationIndexRoute =
  AuthenticatedEducationIndexRouteImport.update({
    id: '/education/',
    path: '/education/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEducationEducationIdRoute =
  AuthenticatedEducationEducationIdRouteImport.update({
    id: '/education/$educationId',
    path: '/education/$educationId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEducationNewRoute =
  AuthenticatedEducationNewRouteImport.update({
    id: '/education/new',
    path: '/education/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedErrorsErrorRoute =
  AuthenticatedErrorsErrorRouteImport.update({
    id: '/errors/$error',
    path: '/errors/$error',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedExperiencesIndexRoute =
  AuthenticatedExperiencesIndexRouteImport.update({
    id: '/experiences/',
    path: '/experiences/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedExperiencesExperienceIdRoute =
  AuthenticatedExperiencesExperienceIdRouteImport.update({
    id: '/experiences/$experienceId',
    path: '/experiences/$experienceId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedExperiencesNewRoute =
  AuthenticatedExperiencesNewRouteImport.update({
    id: '/experiences/new',
    path: '/experiences/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHeroIndexRoute = AuthenticatedHeroIndexRouteImport.update({
  id: '/hero/',
  path: '/hero/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHeroHeroIdRoute = AuthenticatedHeroHeroIdRouteImport.update({
  id: '/hero/$heroId',
  path: '/hero/$heroId',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHeroNewRoute = AuthenticatedHeroNewRouteImport.update({
  id: '/hero/new',
  path: '/hero/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProjectsIndexRoute =
  AuthenticatedProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsProjectIdRoute =
  AuthenticatedProjectsProjectIdRouteImport.update({
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsNewRoute =
  AuthenticatedProjectsNewRouteImport.update({
    id: '/projects/new',
    path: '/projects/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAccountRoute =
  AuthenticatedSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSkillsIndexRoute =
  AuthenticatedSkillsIndexRouteImport.update({
    id: '/skills/',
    path: '/skills/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSkillsSkillIdRoute =
  AuthenticatedSkillsSkillIdRouteImport.update({
    id: '/skills/$skillId',
    path: '/skills/$skillId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSkillsNewRoute = AuthenticatedSkillsNewRouteImport.update({
  id: '/skills/new',
  path: '/skills/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/experience/$experienceId': typeof ExperienceExperienceIdRoute
  '/project/$projectId': typeof ProjectProjectIdRoute
  '/about/$aboutId': typeof AuthenticatedAboutAboutIdRoute
  '/about/new': typeof AuthenticatedAboutNewRoute
  '/education/$educationId': typeof AuthenticatedEducationEducationIdRoute
  '/education/new': typeof AuthenticatedEducationNewRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/experiences/$experienceId': typeof AuthenticatedExperiencesExperienceIdRoute
  '/experiences/new': typeof AuthenticatedExperiencesNewRoute
  '/hero/$heroId': typeof AuthenticatedHeroHeroIdRoute
  '/hero/new': typeof AuthenticatedHeroNewRoute
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdRoute
  '/projects/new': typeof AuthenticatedProjectsNewRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/skills/$skillId': typeof AuthenticatedSkillsSkillIdRoute
  '/skills/new': typeof AuthenticatedSkillsNewRoute
  '/about/': typeof AuthenticatedAboutIndexRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/education/': typeof AuthenticatedEducationIndexRoute
  '/experiences/': typeof AuthenticatedExperiencesIndexRoute
  '/hero/': typeof AuthenticatedHeroIndexRoute
  '/projects/': typeof AuthenticatedProjectsIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/skills/': typeof AuthenticatedSkillsIndexRoute
  '/users/': typeof AuthenticatedUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/experience/$experienceId': typeof ExperienceExperienceIdRoute
  '/project/$projectId': typeof ProjectProjectIdRoute
  '/about/$aboutId': typeof AuthenticatedAboutAboutIdRoute
  '/about/new': typeof AuthenticatedAboutNewRoute
  '/education/$educationId': typeof AuthenticatedEducationEducationIdRoute
  '/education/new': typeof AuthenticatedEducationNewRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/experiences/$experienceId': typeof AuthenticatedExperiencesExperienceIdRoute
  '/experiences/new': typeof AuthenticatedExperiencesNewRoute
  '/hero/$heroId': typeof AuthenticatedHeroHeroIdRoute
  '/hero/new': typeof AuthenticatedHeroNewRoute
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdRoute
  '/projects/new': typeof AuthenticatedProjectsNewRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/skills/$skillId': typeof AuthenticatedSkillsSkillIdRoute
  '/skills/new': typeof AuthenticatedSkillsNewRoute
  '/about': typeof AuthenticatedAboutIndexRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/education': typeof AuthenticatedEducationIndexRoute
  '/experiences': typeof AuthenticatedExperiencesIndexRoute
  '/hero': typeof AuthenticatedHeroIndexRoute
  '/projects': typeof AuthenticatedProjectsIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/skills': typeof AuthenticatedSkillsIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/experience/$experienceId': typeof ExperienceExperienceIdRoute
  '/project/$projectId': typeof ProjectProjectIdRoute
  '/_authenticated/about/$aboutId': typeof AuthenticatedAboutAboutIdRoute
  '/_authenticated/about/new': typeof AuthenticatedAboutNewRoute
  '/_authenticated/education/$educationId': typeof AuthenticatedEducationEducationIdRoute
  '/_authenticated/education/new': typeof AuthenticatedEducationNewRoute
  '/_authenticated/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/_authenticated/experiences/$experienceId': typeof AuthenticatedExperiencesExperienceIdRoute
  '/_authenticated/experiences/new': typeof AuthenticatedExperiencesNewRoute
  '/_authenticated/hero/$heroId': typeof AuthenticatedHeroHeroIdRoute
  '/_authenticated/hero/new': typeof AuthenticatedHeroNewRoute
  '/_authenticated/projects/$projectId': typeof AuthenticatedProjectsProjectIdRoute
  '/_authenticated/projects/new': typeof AuthenticatedProjectsNewRoute
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/_authenticated/skills/$skillId': typeof AuthenticatedSkillsSkillIdRoute
  '/_authenticated/skills/new': typeof AuthenticatedSkillsNewRoute
  '/_authenticated/about/': typeof AuthenticatedAboutIndexRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/education/': typeof AuthenticatedEducationIndexRoute
  '/_authenticated/experiences/': typeof AuthenticatedExperiencesIndexRoute
  '/_authenticated/hero/': typeof AuthenticatedHeroIndexRoute
  '/_authenticated/projects/': typeof AuthenticatedProjectsIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/skills/': typeof AuthenticatedSkillsIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/experience/$experienceId'
    | '/project/$projectId'
    | '/about/$aboutId'
    | '/about/new'
    | '/education/$educationId'
    | '/education/new'
    | '/errors/$error'
    | '/experiences/$experienceId'
    | '/experiences/new'
    | '/hero/$heroId'
    | '/hero/new'
    | '/projects/$projectId'
    | '/projects/new'
    | '/settings/account'
    | '/skills/$skillId'
    | '/skills/new'
    | '/about/'
    | '/dashboard/'
    | '/education/'
    | '/experiences/'
    | '/hero/'
    | '/projects/'
    | '/settings/'
    | '/skills/'
    | '/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/experience/$experienceId'
    | '/project/$projectId'
    | '/about/$aboutId'
    | '/about/new'
    | '/education/$educationId'
    | '/education/new'
    | '/errors/$error'
    | '/experiences/$experienceId'
    | '/experiences/new'
    | '/hero/$heroId'
    | '/hero/new'
    | '/projects/$projectId'
    | '/projects/new'
    | '/settings/account'
    | '/skills/$skillId'
    | '/skills/new'
    | '/about'
    | '/dashboard'
    | '/education'
    | '/experiences'
    | '/hero'
    | '/projects'
    | '/settings'
    | '/skills'
    | '/users'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/settings'
    | '/(auth)/forgot-password'
    | '/(auth)/otp'
    | '/(auth)/sign-in'
    | '/(auth)/sign-up'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/experience/$experienceId'
    | '/project/$projectId'
    | '/_authenticated/about/$aboutId'
    | '/_authenticated/about/new'
    | '/_authenticated/education/$educationId'
    | '/_authenticated/education/new'
    | '/_authenticated/errors/$error'
    | '/_authenticated/experiences/$experienceId'
    | '/_authenticated/experiences/new'
    | '/_authenticated/hero/$heroId'
    | '/_authenticated/hero/new'
    | '/_authenticated/projects/$projectId'
    | '/_authenticated/projects/new'
    | '/_authenticated/settings/account'
    | '/_authenticated/skills/$skillId'
    | '/_authenticated/skills/new'
    | '/_authenticated/about/'
    | '/_authenticated/dashboard/'
    | '/_authenticated/education/'
    | '/_authenticated/experiences/'
    | '/_authenticated/hero/'
    | '/_authenticated/projects/'
    | '/_authenticated/settings/'
    | '/_authenticated/skills/'
    | '/_authenticated/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authOtpRoute: typeof authOtpRoute
  authSignInRoute: typeof authSignInRoute
  authSignUpRoute: typeof authSignUpRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
  ExperienceExperienceIdRoute: typeof ExperienceExperienceIdRoute
  ProjectProjectIdRoute: typeof ProjectProjectIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/experience/$experienceId': {
      id: '/experience/$experienceId'
      path: '/experience/$experienceId'
      fullPath: '/experience/$experienceId'
      preLoaderRoute: typeof ExperienceExperienceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/$projectId': {
      id: '/project/$projectId'
      path: '/project/$projectId'
      fullPath: '/project/$projectId'
      preLoaderRoute: typeof ProjectProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/about/': {
      id: '/_authenticated/about/'
      path: '/about'
      fullPath: '/about/'
      preLoaderRoute: typeof AuthenticatedAboutIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/about/$aboutId': {
      id: '/_authenticated/about/$aboutId'
      path: '/about/$aboutId'
      fullPath: '/about/$aboutId'
      preLoaderRoute: typeof AuthenticatedAboutAboutIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/about/new': {
      id: '/_authenticated/about/new'
      path: '/about/new'
      fullPath: '/about/new'
      preLoaderRoute: typeof AuthenticatedAboutNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/education/': {
      id: '/_authenticated/education/'
      path: '/education'
      fullPath: '/education/'
      preLoaderRoute: typeof AuthenticatedEducationIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/education/$educationId': {
      id: '/_authenticated/education/$educationId'
      path: '/education/$educationId'
      fullPath: '/education/$educationId'
      preLoaderRoute: typeof AuthenticatedEducationEducationIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/education/new': {
      id: '/_authenticated/education/new'
      path: '/education/new'
      fullPath: '/education/new'
      preLoaderRoute: typeof AuthenticatedEducationNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/errors/$error': {
      id: '/_authenticated/errors/$error'
      path: '/errors/$error'
      fullPath: '/errors/$error'
      preLoaderRoute: typeof AuthenticatedErrorsErrorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/experiences/': {
      id: '/_authenticated/experiences/'
      path: '/experiences'
      fullPath: '/experiences/'
      preLoaderRoute: typeof AuthenticatedExperiencesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/experiences/$experienceId': {
      id: '/_authenticated/experiences/$experienceId'
      path: '/experiences/$experienceId'
      fullPath: '/experiences/$experienceId'
      preLoaderRoute: typeof AuthenticatedExperiencesExperienceIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/experiences/new': {
      id: '/_authenticated/experiences/new'
      path: '/experiences/new'
      fullPath: '/experiences/new'
      preLoaderRoute: typeof AuthenticatedExperiencesNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hero/': {
      id: '/_authenticated/hero/'
      path: '/hero'
      fullPath: '/hero/'
      preLoaderRoute: typeof AuthenticatedHeroIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hero/$heroId': {
      id: '/_authenticated/hero/$heroId'
      path: '/hero/$heroId'
      fullPath: '/hero/$heroId'
      preLoaderRoute: typeof AuthenticatedHeroHeroIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hero/new': {
      id: '/_authenticated/hero/new'
      path: '/hero/new'
      fullPath: '/hero/new'
      preLoaderRoute: typeof AuthenticatedHeroNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/': {
      id: '/_authenticated/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AuthenticatedProjectsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/$projectId': {
      id: '/_authenticated/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/new': {
      id: '/_authenticated/projects/new'
      path: '/projects/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof AuthenticatedProjectsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/skills/': {
      id: '/_authenticated/skills/'
      path: '/skills'
      fullPath: '/skills/'
      preLoaderRoute: typeof AuthenticatedSkillsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/skills/$skillId': {
      id: '/_authenticated/skills/$skillId'
      path: '/skills/$skillId'
      fullPath: '/skills/$skillId'
      preLoaderRoute: typeof AuthenticatedSkillsSkillIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/skills/new': {
      id: '/_authenticated/skills/new'
      path: '/skills/new'
      fullPath: '/skills/new'
      preLoaderRoute: typeof AuthenticatedSkillsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsAccountRoute: typeof AuthenticatedSettingsAccountRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsAccountRoute: AuthenticatedSettingsAccountRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedAboutAboutIdRoute: typeof AuthenticatedAboutAboutIdRoute
  AuthenticatedAboutNewRoute: typeof AuthenticatedAboutNewRoute
  AuthenticatedEducationEducationIdRoute: typeof AuthenticatedEducationEducationIdRoute
  AuthenticatedEducationNewRoute: typeof AuthenticatedEducationNewRoute
  AuthenticatedErrorsErrorRoute: typeof AuthenticatedErrorsErrorRoute
  AuthenticatedExperiencesExperienceIdRoute: typeof AuthenticatedExperiencesExperienceIdRoute
  AuthenticatedExperiencesNewRoute: typeof AuthenticatedExperiencesNewRoute
  AuthenticatedHeroHeroIdRoute: typeof AuthenticatedHeroHeroIdRoute
  AuthenticatedHeroNewRoute: typeof AuthenticatedHeroNewRoute
  AuthenticatedProjectsProjectIdRoute: typeof AuthenticatedProjectsProjectIdRoute
  AuthenticatedProjectsNewRoute: typeof AuthenticatedProjectsNewRoute
  AuthenticatedSkillsSkillIdRoute: typeof AuthenticatedSkillsSkillIdRoute
  AuthenticatedSkillsNewRoute: typeof AuthenticatedSkillsNewRoute
  AuthenticatedAboutIndexRoute: typeof AuthenticatedAboutIndexRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
  AuthenticatedEducationIndexRoute: typeof AuthenticatedEducationIndexRoute
  AuthenticatedExperiencesIndexRoute: typeof AuthenticatedExperiencesIndexRoute
  AuthenticatedHeroIndexRoute: typeof AuthenticatedHeroIndexRoute
  AuthenticatedProjectsIndexRoute: typeof AuthenticatedProjectsIndexRoute
  AuthenticatedSkillsIndexRoute: typeof AuthenticatedSkillsIndexRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedAboutAboutIdRoute: AuthenticatedAboutAboutIdRoute,
  AuthenticatedAboutNewRoute: AuthenticatedAboutNewRoute,
  AuthenticatedEducationEducationIdRoute:
    AuthenticatedEducationEducationIdRoute,
  AuthenticatedEducationNewRoute: AuthenticatedEducationNewRoute,
  AuthenticatedErrorsErrorRoute: AuthenticatedErrorsErrorRoute,
  AuthenticatedExperiencesExperienceIdRoute:
    AuthenticatedExperiencesExperienceIdRoute,
  AuthenticatedExperiencesNewRoute: AuthenticatedExperiencesNewRoute,
  AuthenticatedHeroHeroIdRoute: AuthenticatedHeroHeroIdRoute,
  AuthenticatedHeroNewRoute: AuthenticatedHeroNewRoute,
  AuthenticatedProjectsProjectIdRoute: AuthenticatedProjectsProjectIdRoute,
  AuthenticatedProjectsNewRoute: AuthenticatedProjectsNewRoute,
  AuthenticatedSkillsSkillIdRoute: AuthenticatedSkillsSkillIdRoute,
  AuthenticatedSkillsNewRoute: AuthenticatedSkillsNewRoute,
  AuthenticatedAboutIndexRoute: AuthenticatedAboutIndexRoute,
  AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  AuthenticatedEducationIndexRoute: AuthenticatedEducationIndexRoute,
  AuthenticatedExperiencesIndexRoute: AuthenticatedExperiencesIndexRoute,
  AuthenticatedHeroIndexRoute: AuthenticatedHeroIndexRoute,
  AuthenticatedProjectsIndexRoute: AuthenticatedProjectsIndexRoute,
  AuthenticatedSkillsIndexRoute: AuthenticatedSkillsIndexRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authOtpRoute: authOtpRoute,
  authSignInRoute: authSignInRoute,
  authSignUpRoute: authSignUpRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
  ExperienceExperienceIdRoute: ExperienceExperienceIdRoute,
  ProjectProjectIdRoute: ProjectProjectIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
